title: "Mia's Portfolio"
description: "Data Science Portfolio for Grad School"
theme: jekyll-theme-minimal
baseurl: "" # leave empty if publishing at username.github.io
url: ""     # leave empty for GitHub Pages
